Algoritmo "Hello World"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Marcelo
// Data atual  : 03/09/2025
Var
   // Seção de Declarações das variáveis
   nome: caractere

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva ("Olá! digite o seu nome: ")
   Leia (nome)
   Escreva ("Seja bem vindo ",(nome),"!")
Fimalgoritmo