Algoritmo "Teste de Variável - Números"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var
   idade: inteiro
   altura: real

Inicio
   idade <- 20
   altura <- 1.75

   escreval("Idade inicial: ", idade)
   escreval("Altura inicial: ", altura)

   idade <- 25
   altura <- 1.99

   escreval("Idade atualizada: ", idade)
   escreval("Altura atualizada: ", altura)
Fimalgoritmo
